# Generated by Django 4.2.1 on 2023-06-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answercomment',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answercomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='answerstatus',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerstatus',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='questioncomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='questioncomment',
            name='question',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerComment',
        ),
        migrations.DeleteModel(
            name='AnswerStatus',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionComment',
        ),
    ]
