# Generated by Django 4.2.1 on 2023-05-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_alter_rating_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-pub_date']},
        ),
    ]
