# Generated by Django 4.2.1 on 2023-06-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
